export const freeDictionaryList = { "en-en": "en" };
export const bingList = { "en-zh-Hans": "en-zh-Hans" };
export const yandexList = {
  "be-be": "be-be",
  "be-ru": "be-ru",
  "bg-ru": "bg-ru",
  "cs-cs": "cs-cs",
  "cs-en": "cs-en",
  "cs-ru": "cs-ru",
  "da-en": "da-en",
  "da-ru": "da-ru",
  "de-de": "de-de",
  "de-en": "de-en",
  "de-ru": "de-ru",
  "de-tr": "de-tr",
  "el-en": "el-en",
  "el-ru": "el-ru",
  "en-cs": "en-cs",
  "en-da": "en-da",
  "en-de": "en-de",
  "en-el": "en-el",
  "en-en": "en-en",
  "en-es": "en-es",
  "en-et": "en-et",
  "en-fi": "en-fi",
  "en-fr": "en-fr",
  "en-it": "en-it",
  "en-lt": "en-lt",
  "en-lv": "en-lv",
  "en-nl": "en-nl",
  "en-no": "en-no",
  "en-pt": "en-pt",
  "en-pt-BR": "en-pt-BR",
  "en-ru": "en-ru",
  "en-sk": "en-sk",
  "en-sv": "en-sv",
  "en-tr": "en-tr",
  "en-uk": "en-uk",
  "es-en": "es-en",
  "es-es": "es-es",
  "es-ru": "es-ru",
  "et-en": "et-en",
  "et-ru": "et-ru",
  "fi-en": "fi-en",
  "fi-ru": "fi-ru",
  "fi-fi": "fi-fi",
  "fr-fr": "fr-fr",
  "fr-en": "fr-en",
  "fr-ru": "fr-ru",
  "hu-hu": "hu-hu",
  "hu-ru": "hu-ru",
  "it-en": "it-en",
  "it-it": "it-it",
  "it-ru": "it-ru",
  "lt-en": "lt-en",
  "lt-lt": "lt-lt",
  "lt-ru": "lt-ru",
  "lv-en": "lv-en",
  "lv-ru": "lv-ru",
  "mhr-ru": "mhr-ru",
  "mrj-ru": "mrj-ru",
  "nl-en": "nl-en",
  "nl-ru": "nl-ru",
  "no-en": "no-en",
  "no-ru": "no-ru",
  "pl-ru": "pl-ru",
  "pt-en": "pt-en",
  "pt-ru": "pt-ru",
  "ru-be": "ru-be",
  "ru-bg": "ru-bg",
  "ru-cs": "ru-cs",
  "ru-da": "ru-da",
  "ru-de": "ru-de",
  "ru-el": "ru-el",
  "ru-en": "ru-en",
  "ru-es": "ru-es",
  "ru-et": "ru-et",
  "ru-fi": "ru-fi",
  "ru-fr": "ru-fr",
  "ru-hu": "ru-hu",
  "ru-it": "ru-it",
  "ru-lt": "ru-lt",
  "ru-lv": "ru-lv",
  "ru-mhr": "ru-mhr",
  "ru-mrj": "ru-mrj",
  "ru-nl": "ru-nl",
  "ru-no": "ru-no",
  "ru-pl": "ru-pl",
  "ru-pt": "ru-pt",
  "ru-pt-BR": "ru-pt-BR",
  "ru-ru": "ru-ru",
  "ru-sk": "ru-sk",
  "ru-sv": "ru-sv",
  "ru-tr": "ru-tr",
  "ru-tt": "ru-tt",
  "ru-uk": "ru-uk",
  "ru-zh": "ru-zh",
  "sk-en": "sk-en",
  "sk-ru": "sk-ru",
  "sv-en": "sv-en",
  "sv-ru": "sv-ru",
  "tr-de": "tr-de",
  "tr-en": "tr-en",
  "tr-ru": "tr-ru",
  "tt-ru": "tt-ru",
  "uk-en": "uk-en",
  "uk-ru": "uk-ru",
  "uk-uk": "uk-uk",
  "zh-ru": "zh-ru",
  "emj-ru": "emj-ru",
  "emj-en": "emj-en",
  "emj-fr": "emj-fr",
  "emj-es": "emj-es",
  "emj-tr": "emj-tr",
  "emj-it": "emj-it",
  "emj-pt": "emj-pt",
};
export const dictList = [
  {
    name: "Free Dictionary API",
    url: "https://dictionaryapi.dev/",
    list: freeDictionaryList,
  },
  {
    name: "Yandex.Dictionary",
    url: "https://tech.yandex.com/dictionary",
    list: yandexList,
  },
  {
    name: "Bing Dictionary",
    url: "https://www.bing.com/dict",
    list: bingList,
  },
];
