export const FontCategory = {
  1: "sans-serif",
  2: "monospace",
  3: "serif",
  4: "handwriting",
  5: "display",
};
export const reverseFontCategory = {
  "sans-serif": 1,
  monospace: 2,
  serif: 3,
  handwriting: 4,
  display: 5,
};
export const ChineseFonts = [
  {
    id: "LXGWWenKai-Light",
    fontName: "LXGW Wenkai",
    fontFamily: "LXGW Wenkai",
    style: "Light",
    isVariousFont: false,
    url: "/LXGW_Wenkai/LXGWWenKai-Light.ttf",
  },
  {
    id: "LXGWWenKai-Medium",
    fontName: "LXGW Wenkai",
    fontFamily: "LXGW Wenkai",
    style: "Medium",
    isVariousFont: false,
    url: "/LXGW_Wenkai/LXGWWenKai-Medium.ttf",
  },
  {
    id: "LXGWWenKai-Regular",
    fontName: "LXGW Wenkai",
    fontFamily: "LXGW Wenkai",
    style: "Regular",
    isVariousFont: false,
    url: "/LXGW_Wenkai/LXGWWenKai-Regular.ttf",
  },
  {
    id: "LXGWWenKaiMono-Light",
    fontName: "LXGW Wenkai",
    fontFamily: "LXGW Wenkai",
    style: "Mono Light",
    isVariousFont: false,
    url: "/LXGW_Wenkai/LXGWWenKaiMono-Light.ttf",
  },
  {
    id: "LXGWWenKaiMono-Medium",
    fontName: "LXGW Wenkai",
    fontFamily: "LXGW Wenkai",
    style: "Mono Medium",
    isVariousFont: false,
    url: "/LXGW_Wenkai/LXGWWenKaiMono-Medium.ttf",
  },
  {
    id: "LXGWWenKaiMono-Regular",
    fontName: "LXGW Wenkai",
    fontFamily: "LXGW Wenkai",
    style: "Mono Regular",
    isVariousFont: false,
    url: "/LXGW_Wenkai/LXGWWenKaiMono-Regular.ttf",
  },
  {
    id: "NotoSansSC-Bold",
    fontName: "Noto Sans SC",
    fontFamily: "Noto Sans SC",
    style: "Bold",
    isVariousFont: false,
    url: "/Noto_Sans/NotoSansSC-Bold.ttf",
  },
  {
    id: "NotoSansSC-ExtraLight",
    fontName: "Noto Sans SC",
    fontFamily: "Noto Sans SC",
    style: "ExtraLight",
    isVariousFont: false,
    url: "/Noto_Sans/NotoSansSC-ExtraLight.ttf",
  },
  {
    id: "NotoSansSC-Heavy",
    fontName: "Noto Sans SC",
    fontFamily: "Noto Sans SC",
    style: "Heavy",
    isVariousFont: false,
    url: "/Noto_Sans/NotoSansSC-Heavy.ttf",
  },
  {
    id: "NotoSansSC-Light",
    fontName: "Noto Sans SC",
    fontFamily: "Noto Sans SC",
    style: "Light",
    isVariousFont: false,
    url: "/Noto_Sans/NotoSansSC-Light.ttf",
  },
  {
    id: "NotoSansSC-Medium",
    fontName: "Noto Sans SC",
    fontFamily: "Noto Sans SC",
    style: "Medium",
    isVariousFont: false,
    url: "/Noto_Sans/NotoSansSC-Medium.ttf",
  },
  {
    id: "NotoSansSC-Regular",
    fontName: "Noto Sans SC",
    fontFamily: "Noto Sans SC",
    style: "Regular",
    isVariousFont: false,
    url: "/Noto_Sans/NotoSansSC-Regular.ttf",
  },
  {
    id: "NotoSerifSC-Bold",
    fontName: "Noto Serif SC",
    fontFamily: "Noto Serif SC",
    style: "Bold",
    isVariousFont: false,
    url: "/Noto_Serif/NotoSerifSC-Bold.ttf",
  },
  {
    id: "NotoSerifSC-ExtraLight",
    fontName: "Noto Serif SC",
    fontFamily: "Noto Serif SC",
    style: "ExtraLight",
    isVariousFont: false,
    url: "/Noto_Serif/NotoSerifSC-ExtraLight.ttf",
  },
  {
    id: "NotoSerifSC-Heavy",
    fontName: "Noto Serif SC",
    fontFamily: "Noto Serif SC",
    style: "Heavy",
    isVariousFont: false,
    url: "/Noto_Serif/NotoSerifSC-Heavy.ttf",
  },
  {
    id: "NotoSerifSC-Light",
    fontName: "Noto Serif SC",
    fontFamily: "Noto Serif SC",
    style: "Light",
    isVariousFont: false,
    url: "/Noto_Serif/NotoSerifSC-Light.ttf",
  },
  {
    id: "NotoSerifSC-Medium",
    fontName: "Noto Serif SC",
    fontFamily: "Noto Serif SC",
    style: "Medium",
    isVariousFont: false,
    url: "/Noto_Serif/NotoSerifSC-Medium.ttf",
  },
  {
    id: "NotoSerifSC-Regular",
    fontName: "Noto Serif SC",
    fontFamily: "Noto Serif SC",
    style: "Regular",
    isVariousFont: false,
    url: "/Noto_Serif/NotoSerifSC-Regular.ttf",
  },
  {
    id: "NotoSerifSC-SemiBold",
    fontName: "Noto Serif SC",
    fontFamily: "Noto Serif SC",
    style: "SemiBold",
    isVariousFont: false,
    url: "/Noto_Serif/NotoSerifSC-SemiBold.ttf",
  },
  {
    id: "ZhuqueFangsong-Regular",
    fontName: "Zhuque Fangsong",
    fontFamily: "Zhuque Fangsong",
    style: "Regular",
    isVariousFont: false,
    url: "/ZhuqueFangsong/ZhuqueFangsong-Regular.ttf",
  },
  {
    id: "JingHuaLaoSong-Regular",
    fontName: "Jing Hua Laosong",
    fontFamily: "Jing Hua Laosong",
    style: "Regular",
    isVariousFont: false,
    url: "/JingHuaLaoSong/JingHuaLaoSong-Regular.ttf",
  },
  {
    id: "HuiWenZhengKai",
    fontName: "Hui Wen Zhengkai",
    fontFamily: "Hui Wen Zhengkai",
    style: "Regular",
    isVariousFont: false,
    url: "/HuiWenZhengKai/HuiWenZhengKai.ttf",
  },
  {
    id: "HuiWenFangSong",
    fontName: "Hui Wen Fangsong",
    fontFamily: "Hui Wen Fangsong",
    style: "Regular",
    isVariousFont: false,
    url: "/HuiWenFangSong/HuiWenFangSong.ttf",
  },
];

export const NonChineseFonts = [
  {
    id: "EBGaramond-VF",
    fontName: "EB Garamond",
    fontFamily: "EB Garamond",
    style: "Regular",
    isVariousFont: true,
    url: "/EB_Garamond/EBGaramond-VF.ttf",
  },
  {
    id: "EBGaramond-Italic-VF",
    fontName: "EB Garamond",
    fontFamily: "EB Garamond",
    style: "Italic",
    isVariousFont: true,
    url: "/EB_Garamond/EBGaramond-Italic-VF.ttf",
  },
  {
    id: "Inter-VF",
    fontName: "Inter",
    fontFamily: "Inter",
    style: "Regular",
    isVariousFont: true,
    url: "/Inter/Inter-VF.ttf",
  },
  {
    id: "Inter-Italic-VF",
    fontName: "Inter",
    fontFamily: "Inter",
    style: "Italic",
    isVariousFont: true,
    url: "/Inter/Inter-Italic-VF.ttf",
  },
  {
    id: "Lora-VF",
    fontName: "Lora",
    fontFamily: "Lora",
    style: "Regular",
    isVariousFont: true,
    url: "/Lora/Lora-VF.ttf",
  },
  {
    id: "Lora-Italic-VF",
    fontName: "Lora",
    fontFamily: "Lora",
    style: "Italic",
    isVariousFont: true,
    url: "/Lora/Lora-Italic-VF.ttf",
  },
  {
    id: "Montserrat-VF",
    fontName: "Montserrat",
    fontFamily: "Montserrat",
    style: "Regular",
    isVariousFont: true,
    url: "/Montserrat/Montserrat-VF.ttf",
  },
  {
    id: "Montserrat-Italic-VF",
    fontName: "Montserrat",
    fontFamily: "Montserrat",
    style: "Italic",
    isVariousFont: true,
    url: "/Montserrat/Montserrat-Italic-VF.ttf",
  },
  {
    id: "NotoSans-VF",
    fontName: "Noto Sans",
    fontFamily: "Noto Sans",
    style: "Regular",
    isVariousFont: true,
    url: "/Noto_Sans/NotoSans-VF.ttf",
  },
  {
    id: "NotoSans-Italic-VF",
    fontName: "Noto Sans",
    fontFamily: "Noto Sans",
    style: "Italic",
    isVariousFont: true,
    url: "/Noto_Sans/NotoSans-Italic-VF.ttf",
  },
  {
    id: "NotoSansHK-VF",
    fontName: "Noto Sans HK",
    fontFamily: "Noto Sans",
    style: "Regular",
    isVariousFont: true,
    url: "/Noto_Sans/NotoSansHK-VF.ttf",
  },
  {
    id: "NotoSansJP-VF",
    fontName: "Noto Sans JP",
    fontFamily: "Noto Sans",
    style: "Regular",
    isVariousFont: true,
    url: "/Noto_Sans/NotoSansJP-VF.ttf",
  },
  {
    id: "NotoSansKR-VF",
    fontName: "Noto Sans KR",
    fontFamily: "Noto Sans",
    style: "Regular",
    isVariousFont: true,
    url: "/Noto_Sans/NotoSansKR-VF.ttf",
  },
  {
    id: "NotoSansTC-VF",
    fontName: "Noto Sans TC",
    fontFamily: "Noto Sans",
    style: "Regular",
    isVariousFont: true,
    url: "/Noto_Sans/NotoSansTC-VF.ttf",
  },
  {
    id: "NotoSerif-VF",
    fontName: "Noto Serif",
    fontFamily: "Noto Serif",
    style: "Regular",
    isVariousFont: true,
    url: "/Noto_Serif/NotoSerif-VF.ttf",
  },
  {
    id: "NotoSerif-Italic-VF",
    fontName: "Noto Serif",
    fontFamily: "Noto Serif",
    style: "Italic",
    isVariousFont: true,
    url: "/Noto_Serif/NotoSerif-Italic-VF.ttf",
  },
  {
    id: "NotoSerifHK-VF",
    fontName: "Noto Serif HK",
    fontFamily: "Noto Serif",
    style: "Regular",
    isVariousFont: true,
    url: "/Noto_Serif/NotoSerifHK-VF.ttf",
  },
  {
    id: "NotoSerifJP-VF",
    fontName: "Noto Serif JP",
    fontFamily: "Noto Serif",
    style: "Regular",
    isVariousFont: true,
    url: "/Noto_Serif/NotoSerifJP-VF.ttf",
  },
  {
    id: "NotoSerifKR-VF",
    fontName: "Noto Serif KR",
    fontFamily: "Noto Serif",
    style: "Regular",
    isVariousFont: true,
    url: "/Noto_Serif/NotoSerifKR-VF.ttf",
  },
  {
    id: "NotoSerifTC-VF",
    fontName: "Noto Serif TC",
    fontFamily: "Noto Serif",
    style: "Regular",
    isVariousFont: true,
    url: "/Noto_Serif/NotoSerifTC-VF.ttf",
  },
  {
    id: "OpenSans-VF",
    fontName: "Open Sans",
    fontFamily: "Open Sans",
    style: "Regular",
    isVariousFont: true,
    url: "/Open_Sans/OpenSans-VF.ttf",
  },
  {
    id: "OpenSans-Italic-VF",
    fontName: "Open Sans",
    fontFamily: "Open Sans",
    style: "Italic",
    isVariousFont: true,
    url: "/Open_Sans/OpenSans-Italic-VF.ttf",
  },
  {
    id: "PlayfairDisplay-VF",
    fontName: "Playfair Display",
    fontFamily: "Playfair Display",
    style: "Regular",
    isVariousFont: true,
    url: "/Playfair_Display/PlayfairDisplay-VF.ttf",
  },
  {
    id: "PlayfairDisplay-Italic-VF",
    fontName: "Playfair Display",
    fontFamily: "Playfair Display",
    style: "Italic",
    isVariousFont: true,
    url: "/Playfair_Display/PlayfairDisplay-Italic-VF.ttf",
  },
  {
    id: "Poppins-Black",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "Black",
    isVariousFont: false,
    url: "/Poppins/Poppins-Black.ttf",
  },
  {
    id: "Poppins-BlackItalic",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "Black Italic",
    isVariousFont: false,
    url: "/Poppins/Poppins-BlackItalic.ttf",
  },
  {
    id: "Poppins-Bold",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "Bold",
    isVariousFont: false,
    url: "/Poppins/Poppins-Bold.ttf",
  },
  {
    id: "Poppins-BoldItalic",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "Bold Italic",
    isVariousFont: false,
    url: "/Poppins/Poppins-BoldItalic.ttf",
  },
  {
    id: "Poppins-ExtraBold",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "ExtraBold",
    isVariousFont: false,
    url: "/Poppins/Poppins-ExtraBold.ttf",
  },
  {
    id: "Poppins-ExtraBoldItalic",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "ExtraBold Italic",
    isVariousFont: false,
    url: "/Poppins/Poppins-ExtraBoldItalic.ttf",
  },
  {
    id: "Poppins-ExtraLight",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "ExtraLight",
    isVariousFont: false,
    url: "/Poppins/Poppins-ExtraLight.ttf",
  },
  {
    id: "Poppins-ExtraLightItalic",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "ExtraLight Italic",
    isVariousFont: false,
    url: "/Poppins/Poppins-ExtraLightItalic.ttf",
  },
  {
    id: "Poppins-Italic",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "Italic",
    isVariousFont: false,
    url: "/Poppins/Poppins-Italic.ttf",
  },
  {
    id: "Poppins-Light",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "Light",
    isVariousFont: false,
    url: "/Poppins/Poppins-Light.ttf",
  },
  {
    id: "Poppins-LightItalic",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "Light Italic",
    isVariousFont: false,
    url: "/Poppins/Poppins-LightItalic.ttf",
  },
  {
    id: "Poppins-Medium",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "Medium",
    isVariousFont: false,
    url: "/Poppins/Poppins-Medium.ttf",
  },
  {
    id: "Poppins-MediumItalic",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "Medium Italic",
    isVariousFont: false,
    url: "/Poppins/Poppins-MediumItalic.ttf",
  },
  {
    id: "Poppins-Regular",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "Regular",
    isVariousFont: false,
    url: "/Poppins/Poppins-Regular.ttf",
  },
  {
    id: "Poppins-SemiBold",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "SemiBold",
    isVariousFont: false,
    url: "/Poppins/Poppins-SemiBold.ttf",
  },
  {
    id: "Poppins-SemiBoldItalic",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "SemiBold Italic",
    isVariousFont: false,
    url: "/Poppins/Poppins-SemiBoldItalic.ttf",
  },
  {
    id: "Poppins-Thin",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "Thin",
    isVariousFont: false,
    url: "/Poppins/Poppins-Thin.ttf",
  },
  {
    id: "Poppins-ThinItalic",
    fontName: "Poppins",
    fontFamily: "Poppins",
    style: "Thin Italic",
    isVariousFont: false,
    url: "/Poppins/Poppins-ThinItalic.ttf",
  },
  {
    id: "PTSerif-Bold",
    fontName: "PT Serif",
    fontFamily: "PT Serif",
    style: "Bold",
    isVariousFont: false,
    url: "/PT_Serif/PTSerif-Bold.ttf",
  },
  {
    id: "PTSerif-BoldItalic",
    fontName: "PT Serif",
    fontFamily: "PT Serif",
    style: "Bold Italic",
    isVariousFont: false,
    url: "/PT_Serif/PTSerif-BoldItalic.ttf",
  },
  {
    id: "PTSerif-Italic",
    fontName: "PT Serif",
    fontFamily: "PT Serif",
    style: "Italic",
    isVariousFont: false,
    url: "/PT_Serif/PTSerif-Italic.ttf",
  },
  {
    id: "PTSerif-Regular",
    fontName: "PT Serif",
    fontFamily: "PT Serif",
    style: "Regular",
    isVariousFont: false,
    url: "/PT_Serif/PTSerif-Regular.ttf",
  },
  {
    id: "Quicksand-VF",
    fontName: "Quicksand",
    fontFamily: "Quicksand",
    style: "Regular",
    isVariousFont: true,
    url: "/Quicksand/Quicksand-VF.ttf",
  },
  {
    id: "Roboto-Black",
    fontName: "Roboto",
    fontFamily: "Roboto",
    style: "Black",
    isVariousFont: false,
    url: "/Roboto/Roboto-Black.ttf",
  },
  {
    id: "Roboto-BlackItalic",
    fontName: "Roboto",
    fontFamily: "Roboto",
    style: "Black Italic",
    isVariousFont: false,
    url: "/Roboto/Roboto-BlackItalic.ttf",
  },
  {
    id: "Roboto-Bold",
    fontName: "Roboto",
    fontFamily: "Roboto",
    style: "Bold",
    isVariousFont: false,
    url: "/Roboto/Roboto-Bold.ttf",
  },
  {
    id: "Roboto-BoldItalic",
    fontName: "Roboto",
    fontFamily: "Roboto",
    style: "Bold Italic",
    isVariousFont: false,
    url: "/Roboto/Roboto-BoldItalic.ttf",
  },
  {
    id: "Roboto-Italic",
    fontName: "Roboto",
    fontFamily: "Roboto",
    style: "Italic",
    isVariousFont: false,
    url: "/Roboto/Roboto-Italic.ttf",
  },
  {
    id: "Roboto-Light",
    fontName: "Roboto",
    fontFamily: "Roboto",
    style: "Light",
    isVariousFont: false,
    url: "/Roboto/Roboto-Light.ttf",
  },
  {
    id: "Roboto-LightItalic",
    fontName: "Roboto",
    fontFamily: "Roboto",
    style: "Light Italic",
    isVariousFont: false,
    url: "/Roboto/Roboto-LightItalic.ttf",
  },
  {
    id: "Roboto-Medium",
    fontName: "Roboto",
    fontFamily: "Roboto",
    style: "Medium",
    isVariousFont: false,
    url: "/Roboto/Roboto-Medium.ttf",
  },
  {
    id: "Roboto-MediumItalic",
    fontName: "Roboto",
    fontFamily: "Roboto",
    style: "Medium Italic",
    isVariousFont: false,
    url: "/Roboto/Roboto-MediumItalic.ttf",
  },
  {
    id: "Roboto-Regular",
    fontName: "Roboto",
    fontFamily: "Roboto",
    style: "Regular",
    isVariousFont: false,
    url: "/Roboto/Roboto-Regular.ttf",
  },
  {
    id: "Roboto-Thin",
    fontName: "Roboto",
    fontFamily: "Roboto",
    style: "Thin",
    isVariousFont: false,
    url: "/Roboto/Roboto-Thin.ttf",
  },
  {
    id: "Roboto-ThinItalic",
    fontName: "Roboto",
    fontFamily: "Roboto",
    style: "Thin Italic",
    isVariousFont: false,
    url: "/Roboto/Roboto-ThinItalic.ttf",
  },
  {
    id: "Ubuntu-Bold",
    fontName: "Ubuntu",
    fontFamily: "Ubuntu",
    style: "Bold",
    isVariousFont: false,
    url: "/Ubuntu/Ubuntu-Bold.ttf",
  },
  {
    id: "Ubuntu-BoldItalic",
    fontName: "Ubuntu",
    fontFamily: "Ubuntu",
    style: "Bold Italic",
    isVariousFont: false,
    url: "/Ubuntu/Ubuntu-BoldItalic.ttf",
  },
  {
    id: "Ubuntu-Italic",
    fontName: "Ubuntu",
    fontFamily: "Ubuntu",
    style: "Italic",
    isVariousFont: false,
    url: "/Ubuntu/Ubuntu-Italic.ttf",
  },
  {
    id: "Ubuntu-Light",
    fontName: "Ubuntu",
    fontFamily: "Ubuntu",
    style: "Light",
    isVariousFont: false,
    url: "/Ubuntu/Ubuntu-Light.ttf",
  },
  {
    id: "Ubuntu-LightItalic",
    fontName: "Ubuntu",
    fontFamily: "Ubuntu",
    style: "Light Italic",
    isVariousFont: false,
    url: "/Ubuntu/Ubuntu-LightItalic.ttf",
  },
  {
    id: "Ubuntu-Medium",
    fontName: "Ubuntu",
    fontFamily: "Ubuntu",
    style: "Medium",
    isVariousFont: false,
    url: "/Ubuntu/Ubuntu-Medium.ttf",
  },
  {
    id: "Ubuntu-MediumItalic",
    fontName: "Ubuntu",
    fontFamily: "Ubuntu",
    style: "Medium Italic",
    isVariousFont: false,
    url: "/Ubuntu/Ubuntu-MediumItalic.ttf",
  },
  {
    id: "Ubuntu-Regular",
    fontName: "Ubuntu",
    fontFamily: "Ubuntu",
    style: "Regular",
    isVariousFont: false,
    url: "/Ubuntu/Ubuntu-Regular.ttf",
  },
];
