name: Feature Request
description: What feature do you think is missing in Koodo Reader
labels: "feature request"
body:
  - type: checkboxes
    id: testing1
    attributes:
      label: I've searched the issue list, there is no similar features.
      options:
        - label: "Yes"
          required: true

  - type: checkboxes
    id: testing2
    attributes:
      label: If you have more than one feature, please open multiple issues to report respectively.
      options:
        - label: "Yes"
          required: true

  - type: textarea
    id: introduction
    attributes:
      label: Brief Introduction
      placeholder: Brief introduction to this feature
    validations:
      required: true

  - type: textarea
    id: detail
    attributes:
      label: Details
      placeholder: More details about this feature
    validations:
      required: true
