name: 提交Bug
description: 我在使用 Koodo Reader 时遇到了Bug
labels: "bug"
body:
  - type: checkboxes
    id: testing1
    attributes:
      label: 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在
      description: https://github.com/troyeguo/koodo-reader/releases/latest
      options:
        - label: "Yes"
          required: true

  - type: checkboxes
    id: testing2
    attributes:
      label: 我已经搜索了已有的 issue 列表，没有找到类似的 issue
      options:
        - label: "Yes"
          required: true

  - type: checkboxes
    id: testing3
    attributes:
      label: 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决
      description: https://troyeguo.notion.site/Koodo-Reader-0c9c7ccdc5104a54825dfc72f1c84bea
      options:
        - label: "Yes"
          required: true

  - type: dropdown
    id: os
    attributes:
      label: 操作系统或浏览器
      options:
        - Windows 10 及以下
        - Windows 11
        - macOS 10 及以下
        - macOS 11
        - macOS 12
        - Ubuntu
        - 其他 Linux 发行版
        - Chrome 及其他 Chromium 浏览器(包括 Edge 和所有国产浏览器)
        - Firefox
        - IE
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Koodo Reader 版本
      placeholder: 您可以在设置->版本号查看
    validations:
      required: true

  - type: textarea
    id: bug
    attributes:
      label: 我遇到的问题
      placeholder: 描述您遇到的问题以及如何复现该问题
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: 截图或录像(可选的)
      placeholder: 将截图或录像文件拖动到这里上传
    validations:
      required: false

  - type: textarea
    id: download
    attributes:
      label: 图书文件(可选的)
      placeholder: 将文件压缩为zip包后，点击此对话框，拖拽压缩包到此处上传
    validations:
      required: false
