name: Feature Request1
description: 我希望 Koodo Reader 增加这个功能
labels: "feature request"
body:
  - type: checkboxes
    id: testing1
    attributes:
      label: 我已经阅读了Koodo的开发计划，没有找到类似的需求
      description: https://www.notion.so/troyeguo/215baeda57804fd29dbb0e91d1e6a021?v=360c00183d944b598668f34c255edfd7
      options:
        - label: "是"
    validations:
      required: true

  - type: checkboxes
    id: testing2
    attributes:
      label: 这个Issue没有同时提多个需求.
      options:
        - label: "是"
    validations:
      required: true

  - type: textarea
    id: introduction
    attributes:
      label: 简单介绍
      placeholder: 关于这个需求的简单介绍
    validations:
      required: true

  - type: textarea
    id: detail
    attributes:
      label: 细节描述
      placeholder: 关于这个需求的细节描述
    validations:
      required: true
